Feature/jls 6210515296/new nci2i page
blackberggroup/VA-National-Centers pull request #15
Opened 2024-05-31 11:18 UTC by ecstech-admin

## What type of PR is this? (check all applicable)

- [x] Feature
- [ ] Bug Fix
- [ ] Hot Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Develop newly designed NCI2I page

## Related Tickets & Documents
- Monday Task #6210515296
- https://blackberg-group.monday.com/boards/1931719392/pulses/6210515296

## QA Instructions, Screenshots, Recordings
Compare developed page to Figma design
Confirm carousel, map and page, in general functions correctly at different break points

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [Google Lighthouse](https://developer.chrome.com/docs/lighthouse/overview) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

## Are there any post deployment tasks we need to perform?
- Add GA code on production
- Proper meta tags utilized

2024-05-31 14:52 UTC, RyanCrux commented
Couple things:

-  Arrow button on news stories is missing on mobile:
<img width="778" alt="Screenshot 2024-05-31 at 10 46 19 AM" src="https://github.com/blackberggroup/VA-National-Centers/assets/153299181/adfaa99f-1c2b-4556-b048-bcc0afe5f1b5">

- There is a small paragraph of text (only on mobile) that is missing under the news header
<img width="862" alt="Screenshot 2024-05-31 at 10 45 56 AM" src="https://github.com/blackberggroup/VA-National-Centers/assets/153299181/b2a9901e-ebb5-4511-a5bd-4ca2b70483fe">

-button styling under photo images doesn't match figma
<img width="1176" alt="Screenshot 2024-05-31 at 10 43 06 AM" src="https://github.com/blackberggroup/VA-National-Centers/assets/153299181/e8b18659-deaf-49be-bd0d-1d19162af681">

- This is probably because the locations may have been updated but the location copy info doesn't match source
<img width="1331" alt="Screenshot 2024-05-31 at 10 43 33 AM" src="https://github.com/blackberggroup/VA-National-Centers/assets/153299181/beafc641-872e-4196-b6ff-63d4d6ba0224">

- Arrow distance moves with screen size and eventually overlaps  
<img width="763" alt="Screenshot 2024-05-31 at 10 41 13 AM" src="https://github.com/blackberggroup/VA-National-Centers/assets/153299181/7e10b6f2-05e1-4bea-b311-ab14bb15fc43">

Overall looking really good! These pages are going to bring such a nice refresh!

2024-06-03 15:07 UTC, ecstech-admin commented
Hero carousel:
button styles corrected
rm extra padding between carousel and Our Mission

Map:
location edit: NECIE in Manchester NH (from Monday)
(note: static locations mirror popup style with name bold and other info not bold)

News:
Copy from Figma mobile is a mistake: held over from OAM design. 
Fixed styles so nav buttons are available at all breaks.

2024-06-03 21:35 UTC, RyanCrux commented
carousel photo placeholders are smaller than figma:
<img width="531" alt="Screenshot 2024-06-03 at 5 29 39 PM" src="https://github.com/blackberggroup/VA-National-Centers/assets/153299181/bfef17ac-2dd9-43e3-8482-de523dbb1105">

Map moves and cuts off when selecting location:
<img width="999" alt="Screenshot 2024-06-03 at 5 31 16 PM" src="https://github.com/blackberggroup/VA-National-Centers/assets/153299181/ea085d11-8327-4f41-8b62-ebd056502346">

forward/back buttons look better in many places but still overlap in one:
<img width="252" alt="Screenshot 2024-06-03 at 5 32 14 PM" src="https://github.com/blackberggroup/VA-National-Centers/assets/153299181/ec9e2fb5-aac6-42ab-9245-a19d1ef4a3fc">

2024-06-04 14:00 UTC, RyanCrux approved these changes

2024-06-04 14:35 UTC, will-bbg commented on _includes/home/masthead.html
> +<!-- AWARDS - START
Remove commented code. This should not make it to production.

2024-06-04 14:36 UTC, will-bbg commented on _includes/home/masthead.html
> +                            <!-- <img src="assets/img/home/nci2i-1.jpg" class="img-fluid" alt="NCI2I group photo" /> -->
Remove commented code. This should not make it to production.

2024-06-04 14:37 UTC, will-bbg commented on _includes/home/our-mission.html
> +<!-- <section id="our-mission">
Remove commented code. This should not make it to production.

2024-06-04 15:02 UTC, will-bbg requested changes
### Masthead
- Masthead has an "h2". Make it an h1".
- On tablet, prev/next buttons appear out of nowhere. Please double check.
![Screenshot 2024-06-04 at 10 01 44 AM](https://github.com/blackberggroup/VA-National-Centers/assets/145696026/ea987ec3-1c52-44ec-a5ed-6f3a27ed1b64)

### Our Mission
- Reduce Our Mission section padding. Mockup shows 80px.
![Screenshot 2024-06-04 at 9 47 37 AM](https://github.com/blackberggroup/VA-National-Centers/assets/145696026/19980152-fe61-42ab-8b0d-068610473e3e)
- Our Mission should be an "h2" not an "h1"

### Logo Section
- Make logos link to websites
- Add alt tags to logo images
- Logo titles do not match the size in mockup
- Double check padding below logo titles for tablet and mobile. Currently does not match mockup

### News and Events
- Title should be an "h2" not an "h1"
- Let's remove the Dr. Osborne article. He is not longer with the program and was asked to be remove from NCCHI as well
- On mobile, buttons are too close to each other. Please see mockup.

2024-06-04 23:16 UTC, ecstech-admin commented
Made masthead title h1 (with h2 style) ((**This will need to be done on other pages (IDEAS, DRHCI, VA Ventures)**)
Added breaks for carousel arrow buttons and adjusted positioning as needed

Adjusted "Our Mission" padding to match Figma and made title h2 (with h1 style) ((**This will need to be done on other pages (IDEAS, DRHCI, VA Ventures**))

I added link + alt tags to logo images
Adjusted logo title sizes to match Figma size and padding

Made "News and Events" title h2
Removed 4th news article (Dr. Osborne)
Added breaks and adjusted positioning for carousel buttons

2024-06-05 12:04 UTC, will-bbg approved these changes

2024-06-05 12:55 UTC, merged